### ISSUE TITLE
스택의 크기가 켜지면 `pop:` 아래 빈 공간이 커집니다.

### ISSUE THREAD

**Issue by dukhyungkim** [zjoker120/study-vue#3]
<img width="990" alt="Pasted_Image_2023_08_22_21_45" src="https://github.com/zjoker120/study-vue/assets/2559358/65226c94-7360-40d1-a724-09d589fbcc4c">

**Comment by zjoker120** [comment]
Select Type과 Size 표시 움직이지 않도록 했습니다.
