### ISSUE TITLE
type 선택을 하지 않았는데 생성 버튼을 누르면 진행됩니다.

### ISSUE THREAD

**Issue by dukhyungkim** [zjoker120/study-vue#4]
<img width="852" alt="image" src="https://github.com/zjoker120/study-vue/assets/2559358/10cd318b-43fb-478e-b508-0e277cf6b857">

**Comment by zjoker120** [comment]
초기 화면에서 문자열을 check된 상태로 바꾸었습니다. 새로고침해도 문자열로 선택되어있도록 했습니다.
