### ISSUE TITLE
숫자가 입력되지 않습니다.

### ISSUE THREAD

**Issue by dukhyungkim** [zjoker120/study-vue#5]
문자열 선택 -> 생성 -> 입력칸에 숫자가 입력되지 않음.

<img width="273" alt="image" src="https://github.com/zjoker120/study-vue/assets/2559358/bbbbacc2-8a91-4abd-82b3-9f9c9929eae7">

**Comment by zjoker120** [comment]
문자열 선택시 문자+숫자 다 입력 가능하도록 수정했습니다
